steps:
- name: 'abdennour/eksctl:0.16.0-aws-1.18.39-kubectl-v1.18.1'
  entrypoint: 'bash'
  args: ['run.sh']
  secretEnv: ['AWS_ACCESS_KEY_ID', 'AWS_SECRET_ACCESS_KEY']
timeout: 1800s
secrets:
- kmsKeyName: 
  secretEnv:
    AWS_ACCESS_KEY_ID: 
    AWS_SECRET_ACCESS_KEY: 
