apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kaygee-dev
  region: eu-west-2
  version: "1.15"

vpc:
  clusterEndpoints:
    publicAccess: true
    privateAccess: false
  nat:
    gateway: Disable

managedNodeGroups:
- name: ng-1
  instanceType: t3.medium
  minSize: 1
  maxSize: 3
  desiredCapacity: 2
  volumeSize: 25
  ssh:
    publicKeyPath: 
  labels: {role: worker}
  tags:
      nodegroup-role: worker
  iam:
    withAddonPolicies:
      autoScaler: true
      externalDNS: true
      certManager: true
      ebs: true
      albIngress: true
      cloudWatch: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]